PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX sosa: <http://www.w3.org/ns/sosa/>
SELECT ?property (COUNT(?observations) AS ?observationCount)
WHERE {
    ?observations a sosa:Observation .
    ?observations sosa:observedProperty ?property .
    ?observationresult <http://qudt.org/schema/qudt/unit> ?unit .
    ?observationresult <http://qudt.org/schema/qudt/numericValue> ?resultnumeric .
    ?observations sosa:hasResult ?observationresult .
    ?observations sosa:hasFeatureOfInterest ?sample .
    ?sample sosa:hasResult ?metadatasample .
}
GROUP BY ?property